"""add is external to app

Revision ID: 5024ccd14016
Revises: 9344154ffd2a
Create Date: 2025-03-22 14:24:06.429887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5024ccd14016'
down_revision: Union[str, None] = '9344154ffd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_application', sa.Column('is_external', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_external', sa.Boolean(), nullable=False))
    op.drop_column('user', 'is_external_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_external_user', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_external')
    op.drop_column('client_application', 'is_external')
    # ### end Alembic commands ###
