fennec:
  outputs:
    dev:
      type: duckdb
      extensions:
        - httpfs
        - parquet
      external_root: s3://fennec-data/dev
      secrets:
        - type: s3
          region: us-east-1
          key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('S3_ACCESS_SECRET_KEY') }}"
          endpoint: localhost:9000
          use_ssl: false
          url_style: path
  target: dev