"""create sdmxv2.1 meta tables

Revision ID: 68577fd4b211
Revises: 6346c09ac290
Create Date: 2024-08-15 11:21:20.519092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68577fd4b211'
down_revision: Union[str, None] = '6346c09ac290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdmxv21_categorisation',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_agency_id', sa.String(), nullable=False),
    sa.Column('source_version', sa.String(), nullable=False),
    sa.Column('source_package', sa.String(), nullable=False),
    sa.Column('source_class', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('maintainable_parent_id', sa.String(), nullable=False),
    sa.Column('maintainable_parent_version', sa.String(), nullable=False),
    sa.Column('target_agency_id', sa.String(), nullable=False),
    sa.Column('target_package', sa.String(), nullable=False),
    sa.Column('target_class', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'agency_id', 'version', name=op.f('pk_sdmxv21_categorisation'))
    )
    op.create_table('sdmxv21_categoryscheme',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'agency_id', 'version', name=op.f('pk_sdmxv21_categoryscheme'))
    )
    op.create_table('sdmxv21_codelist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'agency_id', 'version', name=op.f('pk_sdmxv21_codelist'))
    )
    op.create_table('sdmxv21_conceptscheme',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'agency_id', 'version', name=op.f('pk_sdmxv21_conceptscheme'))
    )
    op.create_table('sdmxv21_dataflow',
    sa.Column('structure_id', sa.String(), nullable=True),
    sa.Column('structure_agency_id', sa.String(), nullable=True),
    sa.Column('structure_version', sa.String(), nullable=True),
    sa.Column('structure_package', sa.String(), nullable=True),
    sa.Column('structure_class', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'agency_id', 'version', name=op.f('pk_sdmxv21_dataflow'))
    )
    op.create_table('sdmxv21_datastructure',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'agency_id', 'version', name=op.f('pk_sdmxv21_datastructure'))
    )
    op.create_table('sdmxv21_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('root_url', sa.String(), nullable=False),
    sa.Column('bulk_download', sa.Boolean(), nullable=False),
    sa.Column('skip_categories', sa.Boolean(), nullable=False),
    sa.Column('process_all_agencies', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sdmxv21_provider'))
    )
    op.create_table('sdmxv21_attribute',
    sa.Column('assignment_status', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=True),
    sa.Column('data_structure_id', sa.String(), nullable=False),
    sa.Column('data_structure_agency_id', sa.String(), nullable=False),
    sa.Column('data_structure_version', sa.String(), nullable=False),
    sa.Column('concept_id', sa.String(), nullable=True),
    sa.Column('concept_maintainable_parent_id', sa.String(), nullable=True),
    sa.Column('concept_maintainable_parent_version', sa.String(), nullable=True),
    sa.Column('concept_agency_id', sa.String(), nullable=True),
    sa.Column('concept_package', sa.String(), nullable=True),
    sa.Column('concept_class', sa.String(), nullable=True),
    sa.Column('format_type', sa.String(), nullable=True),
    sa.Column('codelist_id', sa.String(), nullable=True),
    sa.Column('codelist_agency_id', sa.String(), nullable=True),
    sa.Column('codelist_version', sa.String(), nullable=True),
    sa.Column('codelist_package', sa.String(), nullable=True),
    sa.Column('codelist_class', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_structure_id', 'data_structure_agency_id', 'data_structure_version'], ['sdmxv21_datastructure.id', 'sdmxv21_datastructure.agency_id', 'sdmxv21_datastructure.version'], name=op.f('fk_sdmxv21_attribute_data_structure_id_sdmxv21_datastructure')),
    sa.PrimaryKeyConstraint('id', 'data_structure_id', 'data_structure_agency_id', 'data_structure_version', name=op.f('pk_sdmxv21_attribute'))
    )
    op.create_table('sdmxv21_category',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=True),
    sa.Column('category_scheme_id', sa.String(), nullable=False),
    sa.Column('category_scheme_agency_id', sa.String(), nullable=False),
    sa.Column('category_scheme_version', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('parent_scheme_id', sa.String(), nullable=True),
    sa.Column('parent_scheme_agency_id', sa.String(), nullable=True),
    sa.Column('parent_scheme_version', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_scheme_id', 'category_scheme_agency_id', 'category_scheme_version'], ['sdmxv21_categoryscheme.id', 'sdmxv21_categoryscheme.agency_id', 'sdmxv21_categoryscheme.version'], name=op.f('fk_sdmxv21_category_category_scheme_id_sdmxv21_categoryscheme')),
    sa.ForeignKeyConstraint(['parent_id', 'parent_scheme_id', 'parent_scheme_agency_id', 'parent_scheme_version'], ['sdmxv21_category.id', 'sdmxv21_category.category_scheme_id', 'sdmxv21_category.category_scheme_agency_id', 'sdmxv21_category.category_scheme_version'], name=op.f('fk_sdmxv21_category_parent_id_sdmxv21_category')),
    sa.PrimaryKeyConstraint('id', 'category_scheme_id', 'category_scheme_agency_id', 'category_scheme_version', name=op.f('pk_sdmxv21_category'))
    )
    op.create_table('sdmxv21_code',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=True),
    sa.Column('codelist_id', sa.String(), nullable=False),
    sa.Column('codelist_agency_id', sa.String(), nullable=False),
    sa.Column('codelist_version', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['codelist_id', 'codelist_agency_id', 'codelist_version'], ['sdmxv21_codelist.id', 'sdmxv21_codelist.agency_id', 'sdmxv21_codelist.version'], name=op.f('fk_sdmxv21_code_codelist_id_sdmxv21_codelist')),
    sa.PrimaryKeyConstraint('id', 'codelist_id', 'codelist_agency_id', 'codelist_version', name=op.f('pk_sdmxv21_code'))
    )
    op.create_table('sdmxv21_concept',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=True),
    sa.Column('concept_scheme_id', sa.String(), nullable=False),
    sa.Column('concept_scheme_agency_id', sa.String(), nullable=False),
    sa.Column('concept_scheme_version', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['concept_scheme_id', 'concept_scheme_agency_id', 'concept_scheme_version'], ['sdmxv21_conceptscheme.id', 'sdmxv21_conceptscheme.agency_id', 'sdmxv21_conceptscheme.version'], name=op.f('fk_sdmxv21_concept_concept_scheme_id_sdmxv21_conceptscheme')),
    sa.PrimaryKeyConstraint('id', 'concept_scheme_id', 'concept_scheme_agency_id', 'concept_scheme_version', name=op.f('pk_sdmxv21_concept'))
    )
    op.create_table('sdmxv21_dimension',
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=True),
    sa.Column('data_structure_id', sa.String(), nullable=False),
    sa.Column('data_structure_agency_id', sa.String(), nullable=False),
    sa.Column('data_structure_version', sa.String(), nullable=False),
    sa.Column('concept_id', sa.String(), nullable=True),
    sa.Column('concept_maintainable_parent_id', sa.String(), nullable=True),
    sa.Column('concept_maintainable_parent_version', sa.String(), nullable=True),
    sa.Column('concept_agency_id', sa.String(), nullable=True),
    sa.Column('concept_package', sa.String(), nullable=True),
    sa.Column('concept_class', sa.String(), nullable=True),
    sa.Column('format_type', sa.String(), nullable=True),
    sa.Column('codelist_id', sa.String(), nullable=True),
    sa.Column('codelist_agency_id', sa.String(), nullable=True),
    sa.Column('codelist_version', sa.String(), nullable=True),
    sa.Column('codelist_package', sa.String(), nullable=True),
    sa.Column('codelist_class', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_structure_id', 'data_structure_agency_id', 'data_structure_version'], ['sdmxv21_datastructure.id', 'sdmxv21_datastructure.agency_id', 'sdmxv21_datastructure.version'], name=op.f('fk_sdmxv21_dimension_data_structure_id_sdmxv21_datastructure')),
    sa.PrimaryKeyConstraint('id', 'data_structure_id', 'data_structure_agency_id', 'data_structure_version', name=op.f('pk_sdmxv21_dimension'))
    )
    op.create_table('sdmxv21_primary_measure',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=True),
    sa.Column('data_structure_id', sa.String(), nullable=False),
    sa.Column('data_structure_agency_id', sa.String(), nullable=False),
    sa.Column('data_structure_version', sa.String(), nullable=False),
    sa.Column('concept_id', sa.String(), nullable=True),
    sa.Column('concept_maintainable_parent_id', sa.String(), nullable=True),
    sa.Column('concept_maintainable_parent_version', sa.String(), nullable=True),
    sa.Column('concept_agency_id', sa.String(), nullable=True),
    sa.Column('concept_package', sa.String(), nullable=True),
    sa.Column('concept_class', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_structure_id', 'data_structure_agency_id', 'data_structure_version'], ['sdmxv21_datastructure.id', 'sdmxv21_datastructure.agency_id', 'sdmxv21_datastructure.version'], name=op.f('fk_sdmxv21_primary_measure_data_structure_id_sdmxv21_datastructure')),
    sa.PrimaryKeyConstraint('id', 'data_structure_id', 'data_structure_agency_id', 'data_structure_version', name=op.f('pk_sdmxv21_primary_measure'))
    )
    op.create_table('sdmxv21_timedimension',
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=True),
    sa.Column('data_structure_id', sa.String(), nullable=False),
    sa.Column('data_structure_agency_id', sa.String(), nullable=False),
    sa.Column('data_structure_version', sa.String(), nullable=False),
    sa.Column('concept_id', sa.String(), nullable=True),
    sa.Column('concept_maintainable_parent_id', sa.String(), nullable=True),
    sa.Column('concept_maintainable_parent_version', sa.String(), nullable=True),
    sa.Column('concept_agency_id', sa.String(), nullable=True),
    sa.Column('concept_package', sa.String(), nullable=True),
    sa.Column('concept_class', sa.String(), nullable=True),
    sa.Column('format_type', sa.String(), nullable=True),
    sa.Column('codelist_id', sa.String(), nullable=True),
    sa.Column('codelist_agency_id', sa.String(), nullable=True),
    sa.Column('codelist_version', sa.String(), nullable=True),
    sa.Column('codelist_package', sa.String(), nullable=True),
    sa.Column('codelist_class', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_structure_id', 'data_structure_agency_id', 'data_structure_version'], ['sdmxv21_datastructure.id', 'sdmxv21_datastructure.agency_id', 'sdmxv21_datastructure.version'], name=op.f('fk_sdmxv21_timedimension_data_structure_id_sdmxv21_datastructure')),
    sa.PrimaryKeyConstraint('id', 'data_structure_id', 'data_structure_agency_id', 'data_structure_version', name=op.f('pk_sdmxv21_timedimension'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sdmxv21_timedimension')
    op.drop_table('sdmxv21_primary_measure')
    op.drop_table('sdmxv21_dimension')
    op.drop_table('sdmxv21_concept')
    op.drop_table('sdmxv21_code')
    op.drop_table('sdmxv21_category')
    op.drop_table('sdmxv21_attribute')
    op.drop_table('sdmxv21_provider')
    op.drop_table('sdmxv21_datastructure')
    op.drop_table('sdmxv21_dataflow')
    op.drop_table('sdmxv21_conceptscheme')
    op.drop_table('sdmxv21_codelist')
    op.drop_table('sdmxv21_categoryscheme')
    op.drop_table('sdmxv21_categorisation')
    # ### end Alembic commands ###
